before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386

    goarm:
      - 6
      - 7

#    hooks:
#      post:
#        - upx "{{ .Path }}"
checksum:
  name_template: 'checksums.txt'
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
      - "ronix/goreadme:latest"
      - "ronix/goreadme:{{ .Tag }}"
      - "ronix/goreadme:amd64-latest"
      - "ronix/goreadme:amd64-{{ .Tag }}"
    skip_push: true
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    goos: linux
    goarch: arm64
    goarm: ''
    image_templates:
      - "ronix/goreadme:arm64-latest"
      - "ronix/goreadme:arm64-{{ .Tag }}"
    skip_push: true
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm64"
  -
    goos: linux
    goarch: 386
    goarm: ''
    image_templates:
      - "ronix/goreadme:386-latest"
      - "ronix/goreadme:386-{{ .Tag }}"
    skip_push: true
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/386"
