before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    goos:
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm

    goarm:
      - 6
      - 7

  -
    id: "with-upx"
    targets:
      - "linux_amd64"
      - "linux_arm64"
      - "linux_arm_6"
      - "linux_arm_7"
      - "linux_386"
      - "darwin_amd64"
      - "windows_386"
      - "windows_amd64"
    hooks:
      post:
        - upx "{{ .Path }}"
checksum:
  name_template: 'checksums.txt'
dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
      - "docker.io/ronix/goreadme:latest"
      - "docker.io/ronix/goreadme:{{ .Tag }}"
      - "docker.io/ronix/goreadme:amd64-latest"
      - "docker.io/ronix/goreadme:amd64-{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    goos: linux
    goarch: arm64
    goarm: ''
    image_templates:
      - "docker.io/ronix/goreadme:arm64-latest"
      - "docker.io/ronix/goreadme:arm64-{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/arm64"
  -
    goos: linux
    goarch: 386
    goarm: ''
    image_templates:
      - "docker.io/ronix/goreadme:386-latest"
      - "docker.io/ronix/goreadme:386-{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--platform=linux/386"
