before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - 386
#    hooks:
#      post:
#        - upx "{{ .Path }}"
checksum:
  name_template: 'checksums.txt'
